### ISSUE TITLE
I saw your talk, and very interesting. But why use the same paradigm as before?

### ISSUE THREAD

**Issue by foxjazz** [entropic-dev/entropic#201]
Node is an interesting tool, but why stick with old technology when dotnet core works at scale with greater performance than node, coming into version 3?

This is Month old code, and yet it seems no consideration to architecture was even made and we assume Node is best for this.  What a waist.

**Comment by chrisdickinson** [comment]
Hi! Node was specifically selected because both ceej and I are well-practiced in it, and the community we hope to grow around the project is likely to be most comfortable contributing JS. (I had to be talked down from writing portions of this in Rust, likewise ceej and golang. JS is the right fit for this project, though. Alternate registries and clients may appear written in other languages.) Notably: we knew we would end up with multiple services, but wanted to build a single functioning service first and split it out (which is what I’m working on in #135), because of Gall’s law.

I also want to note here: coming into a project, disparaging underlying tech choices, and lamenting the choices made is generally considered to be very rude. Further comments like this will be removed and result in a block.
