### ISSUE TITLE
Is this project dead? Just curious. 

### ISSUE THREAD

**Issue by AdamBD** [entropic-dev/entropic#365]

**Comment by ragecryx** [comment]
Bump, I would like to know too. Installation instructions are broken for some time (like reported in #343 ). And no active discussions here or in discourse for months.

**Comment by petersg83** [comment]
It might be related to Microsoft that bought npm and github recently. Microsoft would want only Github Packages to rule the game...

**Comment by AdamBD** [comment]
was entropic going to only be for .js packages? I imagined what was important here was the federated model, meaning any language could adopt this model for package management.

**Comment by ragecryx** [comment]
> was entropic going to only be for .js packages? I imagined what was important here was the federated model, meaning any language could adopt this model for package management.

I think it is the latter but a lot of it's initial goals is to support the JS community.

I personally was lurking for quite some time now, looking for an opportunity to contribute (felt that I lack the experience on the domain of package management to jump right in) and it makes me a little bit sad to see inactivity. In an internet reality where everything is gradually being walled and centralized projects like this should receive more attention and support from devs.

Even if the case is that the original authors don't have much time to spend on this, I hope they find at least some time to guide/mentor the rest of us to continue the work.

**Comment by petersg83** [comment]
> was entropic going to only be for .js packages? I imagined what was important here was the federated model, meaning any language could adopt this model for package management.

I was thinking it was more about a decentralized registry, meaning that no one has the full control (as it is what npm has for now. You can't really publish your package elsewhere)

**Comment by chrisdickinson** [comment]
Hi folks!

So, yeah, Entropic is dormant right now. The maintainers (myself included!) were trying to balance working on this project in our off hours with our day jobs. Unfortunately, our day jobs ramped up, and the balance split to focusing on our day jobs. I'd love to continue working on this project sometime in the future, when I've got headspace to do so; I imagine this sentiment is shared by the other maintainers. Even in light of the GitHub acquisition, I think decentralized package management is compelling.

You may be interested in [Orogene], which is an attempt to build a new package management CLI for JS packages, led by @zkat. It's still in early days, too.

[Orogene]: https://github.com/orogene/orogene/

**Comment by conartist6** [comment]
I just wanted to say hello because I'm actively working on something that's related to decentralized package development. I'm building a build system called [macrome](https://github.com/macrome-js/macrome). The idea is to create the tooling you would want if your plan was to check all your built code into your git repository. The tools specifically help with cleaning, verifying, and incrementally building a project's generated assets.

Packages built this way can still be published in a central repo, but since the git repo is itself a package it can be forked, have versions owned by different maintainers and hosted different places, and used with (more or less) any up-to-date package manager. The biggest advantage is that you can swap out the implementation behind a name without changing any of your code!

My projects are not quite ready for the world yet, but I am actively working on them as my primary "job". I'm pretty excited about the possibilities that decentralized development might bring, and wanted to thank @ceejbot for her [2019 talk](https://www.youtube.com/watch?v=MO8hZlgK5zc) which got me thinking about this (even if I forgot about it for a while afterwards).
